/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package duantotnghiep.View.ThongKe;

import duantotnghiep.DAO.CRUD;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import org.knowm.xchart.CategoryChart;
import org.knowm.xchart.CategoryChartBuilder;
import org.knowm.xchart.XChartPanel;
import org.knowm.xchart.style.Styler;

/**
 *
 * @author duck
 */
public class ThongKeSoSachDangMuon extends javax.swing.JPanel {


    /**
     * Creates new form ThongKeSoSachDangMuon
     */
    public ThongKeSoSachDangMuon() {
        initComponents();
        setLayout(null);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setPreferredSize(screenSize);
        setSize(screenSize);

        ArrayList<String> chuDe = new ArrayList<>();
        ArrayList<Integer> soLuong = new ArrayList<>();
        fillChartData(chuDe, soLuong);

        CategoryChart chart = new CategoryChartBuilder()
                .width(600)
                .height(350)
                .title("Số lượng sách đang được mượn theo chủ đề")
                .yAxisTitle("Số lượng")
                .xAxisTitle("Chủ đề")
                .build();

        chart.getStyler().setLegendPosition(Styler.LegendPosition.InsideNW);
        chart.getStyler().setLabelsVisible(true);
        chart.getStyler().setYAxisMin(0.0);
        chart.addSeries("Sách", chuDe, soLuong);

        XChartPanel<CategoryChart> chartPanel = new XChartPanel<>(chart);
        chartPanel.setBounds(0, 0, 1400, 640); // Xác định vị trí và kích thước phù hợp
        add(chartPanel);

    }

    public void fillChartData(ArrayList<String> chuDe, ArrayList<Integer> soLuong) {
    String sql = "SELECT cd.TenChuDe, COUNT(ctm.ChiTietMuon_ID) AS SoLuongDangMuon "
               + "FROM ChiTietMuon ctm "
               + "JOIN Sach s ON ctm.Sach_ID = s.SachID "
               + "JOIN ChuDeSach cds ON s.SachID = cds.SachID "
               + "JOIN ChuDe cd ON cds.ChuDeID = cd.ChuDeID "
               + "WHERE ctm.TrangThai = N'Đang mượn' "
               + "GROUP BY cd.TenChuDe "
               + "ORDER BY SoLuongDangMuon DESC";

    try (Connection con = DriverManager.getConnection(CRUD.connectionUrl); 
         PreparedStatement stm = con.prepareStatement(sql);
         ResultSet rs = stm.executeQuery()) {

        while (rs.next()) {
            chuDe.add(rs.getString("TenChuDe"));
            soLuong.add(rs.getInt("SoLuongDangMuon"));
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
