/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package duantotnghiep.View.ThongKe;

import duantotnghiep.DAO.CRUD;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JPanel;
import org.knowm.xchart.CategoryChart;
import org.knowm.xchart.CategoryChartBuilder;
import org.knowm.xchart.XChartPanel;
import org.knowm.xchart.style.Styler;

/**
 *
 * @author duck
 */
public class ThongKeSachDuocMuonNhieuNhat extends javax.swing.JPanel {


    /**
     * Creates new form ThongKeSachDuocMuonNhieuNhat
     */
    public ThongKeSachDuocMuonNhieuNhat() {
        setLayout(new BorderLayout());
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setPreferredSize(screenSize);
        setSize(screenSize);

        ArrayList<String> TenSach = new ArrayList<>();
        ArrayList<Integer> SoLuongMuon = new ArrayList<>();
        fillChartData(TenSach, SoLuongMuon);

        CategoryChart chart = new CategoryChartBuilder()
                .width(600)
                .height(650)
                .title("Số lượng sách đang được mượn nhiều nhất")
                .yAxisTitle("Số lượng")
                .xAxisTitle("Tên sách")
                .build();

        chart.getStyler().setLegendPosition(Styler.LegendPosition.InsideNW);
        chart.getStyler().setLabelsVisible(true);
        chart.getStyler().setYAxisMin(0.0);
        chart.getStyler().setChartPadding(0); // Reduce padding
        chart.getStyler().setPlotMargin(0);   // Reduce margin
        chart.addSeries("Sách", TenSach, SoLuongMuon);

        XChartPanel<CategoryChart> chartPanel = new XChartPanel<>(chart);
        chartPanel.setPreferredSize(new Dimension(750, 400));

// Wrap the chartPanel in a JPanel to control its position
        JPanel wrapperPanel = new JPanel(new BorderLayout());
        wrapperPanel.add(chartPanel, BorderLayout.NORTH);
        JPanel emptyPanel = new JPanel();
        wrapperPanel.add(emptyPanel, BorderLayout.CENTER);

        add(wrapperPanel, BorderLayout.CENTER);
    }

    public void fillChartData(ArrayList<String> TenSach, ArrayList<Integer> soLuong) {
        String sql = "SELECT TOP 10 s.TenSach, COUNT(ctm.Sach_ID) AS SoLuongMuon "
                   + "FROM ChiTietMuon ctm "
                   + "JOIN Sach s ON ctm.Sach_ID = s.SachID "
                   + "GROUP BY s.TenSach "
                   + "ORDER BY SoLuongMuon DESC";

        try (Connection con = DriverManager.getConnection(CRUD.connectionUrl); 
             PreparedStatement stm = con.prepareStatement(sql);
             ResultSet rs = stm.executeQuery()) {

            while (rs.next()) {
                TenSach.add(rs.getString("TenSach"));
                soLuong.add(rs.getInt("SoLuongMuon"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
